# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_todoentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoentry',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todoentry',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
